elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
kibana3:
  image: deviantony/elk-kibana:kibana3
  ports:
    - "8080:80"
  links:
    - elasticsearch
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
